spring:
  application:
    admin:trip-backend
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres"
    username: ${DB_USER_NAME:user}
    password: ${DB_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
       locations: "db/migration"
  threads:
    virtual.enabled: true


server:
  port: 8080

com:
  gauravsalvi:
